import type {
  CostLine,
  Destination,
  EngineSettings,
  FxTable,
  PackagingType,
  ProcessType,
} from './types';
import { DEFAULT_LBS_PER_CONTAINER, trmToUsdPerCop } from './units';

/** Pounds in the 32.5 MT truck load that ground transport is quoted against. */
export const LBS_PER_TRUCK = 71649.5;

/** TRM the source sheet was built on. Overridden by the live rate in production. */
export const SEED_TRM = 3150;

/**
 * The cost stack, transcribed from the Forest Spot Contracts process sheet.
 *
 * Amounts stay in their native currency and native unit — a bag, a container, a
 * truck — exactly as they are invoiced. The engine does the per-pound and FX
 * conversion, so editing a supplier's invoice value in admin needs no maths.
 */
export const SEED_COST_LINES: CostLine[] = [
  {
    key: 'packaging',
    label: 'Packaging',
    group: 'fob',
    basis: 'per_unit',
    driver: 'packaging',
    currency: 'COP',
    amount: 0,
    lbsPerUnit: 0,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 10,
    active: true,
  },
  {
    key: 'grain_pro',
    label: 'Grain Pro liner',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 7240,
    lbsPerUnit: 154.322,
    perMonth: false,
    optional: true,
    defaultOn: true,
    isMargin: false,
    sortOrder: 20,
    active: true,
  },
  {
    key: 'milling',
    label: 'Milling',
    group: 'fob',
    basis: 'per_unit',
    driver: 'process',
    currency: 'COP',
    amount: 0,
    lbsPerUnit: 0,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 30,
    active: true,
  },
  {
    key: 'bag_marks',
    label: 'Bag marks',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 400,
    lbsPerUnit: 154.322,
    perMonth: false,
    optional: true,
    defaultOn: true,
    isMargin: false,
    sortOrder: 40,
    active: true,
  },
  {
    key: 'internal_transport',
    label: 'Internal transport',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 3282815,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 50,
    active: true,
  },
  {
    key: 'ground_transport',
    label: 'Ground transport',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 10000000,
    lbsPerUnit: LBS_PER_TRUCK,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 60,
    active: true,
  },
  {
    key: 'contribution',
    label: 'Contribution',
    group: 'fob',
    basis: 'per_lb',
    driver: 'fixed',
    currency: 'USD',
    amount: 0.06,
    lbsPerUnit: 1,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 70,
    active: true,
  },
  {
    key: 'port_costs',
    label: 'Port costs',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 1200000,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 80,
    active: true,
  },
  {
    key: 'freight_agent',
    label: 'Freight agent',
    group: 'fob',
    basis: 'per_unit',
    driver: 'fixed',
    currency: 'COP',
    amount: 4200000,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 90,
    active: true,
  },
  {
    key: 'gmf',
    label: 'GMF (4x1000)',
    group: 'fob',
    basis: 'per_lb',
    driver: 'fixed',
    currency: 'COP',
    amount: 3.19,
    lbsPerUnit: 1,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 100,
    active: true,
  },
  {
    key: 'fixed_cost',
    label: 'Fixed cost',
    group: 'fob',
    basis: 'per_lb',
    driver: 'fixed',
    currency: 'USD',
    amount: 0.25,
    lbsPerUnit: 1,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 110,
    active: true,
  },
  {
    key: 'seafreight',
    label: 'Ocean freight',
    group: 'freight',
    basis: 'per_unit',
    driver: 'destination',
    currency: 'USD',
    amount: 0,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 120,
    active: true,
  },
  {
    key: 'import_cost',
    label: 'Import cost',
    group: 'import',
    basis: 'per_unit',
    driver: 'destination',
    currency: 'USD',
    amount: 0,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 130,
    active: true,
  },
  {
    key: 'unloading_ddp',
    label: 'Unloading (DDP)',
    group: 'import',
    basis: 'per_unit',
    driver: 'destination',
    currency: 'USD',
    amount: 0,
    lbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    perMonth: false,
    optional: false,
    defaultOn: true,
    isMargin: false,
    sortOrder: 140,
    active: true,
  },
  {
    key: 'storage',
    label: 'Storage',
    group: 'optional',
    basis: 'per_unit',
    driver: 'destination',
    currency: 'USD',
    amount: 0,
    lbsPerUnit: 0,
    perMonth: true,
    optional: true,
    defaultOn: false,
    isMargin: false,
    sortOrder: 150,
    active: true,
  },
  {
    key: 'finance',
    label: 'Finance',
    group: 'optional',
    basis: 'rate',
    driver: 'fixed',
    currency: 'USD',
    amount: 0.0072,
    lbsPerUnit: 1,
    perMonth: true,
    optional: true,
    defaultOn: false,
    isMargin: false,
    sortOrder: 160,
    active: true,
  },
];

export const SEED_PACKAGING: PackagingType[] = [
  {
    key: 'jute_70',
    label: '70 kg jute bag',
    kgPerUnit: 70,
    lbsPerUnit: 154.322,
    amount: 9125,
    currency: 'COP',
    active: true,
  },
  {
    key: 'pack_35',
    label: '35 kg pack',
    kgPerUnit: 35,
    lbsPerUnit: 77.161,
    amount: 24843,
    currency: 'COP',
    active: true,
  },
  {
    key: 'pack_24',
    label: '24 kg pack',
    kgPerUnit: 24,
    lbsPerUnit: 52.9104,
    amount: 25000,
    currency: 'COP',
    active: true,
  },
];

export const SEED_PROCESSES: ProcessType[] = [
  {
    key: 'washed',
    label: 'Washed',
    amount: 50000,
    lbsPerUnit: 154.322,
    currency: 'COP',
    active: true,
  },
  {
    key: 'honey',
    label: 'Honey',
    amount: 70000,
    lbsPerUnit: 154.322,
    currency: 'COP',
    active: true,
  },
  {
    key: 'natural',
    label: 'Natural',
    amount: 90000,
    lbsPerUnit: 154.322,
    currency: 'COP',
    active: true,
  },
];

function dest(
  key: string,
  label: string,
  quoteCurrency: Destination['quoteCurrency'],
  quoteUnit: Destination['quoteUnit'],
  seafreight: number,
  importCost: number,
  storageAmount: number,
  storageCurrency: Destination['storageCurrency'],
): Destination {
  return {
    key,
    label,
    quoteCurrency,
    quoteUnit,
    seafreightAmount: seafreight,
    seafreightCurrency: 'USD',
    seafreightLbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    importAmount: importCost,
    importCurrency: 'USD',
    importLbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    // The sheet leaves unloading blank for every destination; it is wired up so
    // it can be filled in per destination without a code change.
    unloadingAmount: 0,
    unloadingCurrency: 'USD',
    unloadingLbsPerUnit: DEFAULT_LBS_PER_CONTAINER,
    storageAmount,
    storageCurrency,
    allowedIncoterms: ['FOB', 'CIF', 'DDP'],
    active: true,
  };
}

export const SEED_DESTINATIONS: Destination[] = [
  dest('ny', 'New York', 'USD', 'lb', 2500, 2600, 1.05, 'USD'),
  dest('dupuy', 'Dupuy', 'USD', 'lb', 2500, 2100, 1.05, 'USD'),
  dest('annex', 'Annex', 'USD', 'lb', 2500, 2600, 1.05, 'USD'),
  dest('canada', 'Canada', 'CAD', 'kg', 2500, 2500, 1.05, 'USD'),
  dest('australia', 'Australia', 'AUD', 'kg', 4000, 2100, 2.5, 'AUD'),
  dest('rotterdam', 'Rotterdam', 'EUR', 'kg', 2500, 1800, 1.4, 'EUR'),
  dest('uk', 'United Kingdom', 'GBP', 'kg', 2500, 1800, 1.4, 'EUR'),
  // Dubai has no storage rate in the source sheet — left at zero deliberately
  // so the engine warns rather than silently pricing storage at nothing.
  dest('dubai', 'Dubai', 'USD', 'kg', 6000, 2500, 0, 'USD'),
];

export const SEED_SETTINGS: EngineSettings = {
  marginMode: 'on_price',
  marginBase: 'full_landed_cost',
  minMargin: 0.16,
  ladderFrom: 0.2,
  ladderTo: 0.3,
  ladderStep: 0.01,
  financeMonthlyRate: 0.0072,
};

/** Fallback FX, used only until the live rates land. USD per one unit. */
export const SEED_FX: FxTable = {
  USD: 1,
  COP: trmToUsdPerCop(SEED_TRM),
  EUR: 1.09,
  AUD: 0.66,
  GBP: 1.27,
  CAD: 0.73,
};
